services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: bento
      POSTGRES_PASSWORD: bento
      POSTGRES_DB: openroles_development
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: